version: '3.5'

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: db

  web:
    build: .
    volumes:
      - ./:/app/
      - ./static:/app/static/
      - ./media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
       - db
    links:
       - db:db
    container_name: social_web
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data: