# Generated by Django 5.1.2 on 2024-10-19 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('posts', '0003_alter_post_author'),
        ('users', '0002_remove_user_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='user',
            name='bblocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Заблокированные пользователи'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_countries',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='countries.country', verbose_name='Подписанные страны'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_tags',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='posts.tag', verbose_name='Подписанные теги'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписанные пользователи'),
        ),
    ]
